title: HelloDataScience
description: Python, Data Analysis, Data Visualization, Statistical Analysis, Machine Learning, Deep Learning, Time Series, Web Scraping, Text Mining
remote_theme: "mmistakes/minimal-mistakes@master"
plugins: [jekyll-include-cache, jekyll-feed, jekyll-sitemap, jekyll-paginate]
